updated bicep and tf linter

diff --git a/.github/workflows/terraform_linter.yml b/.github/workflows/terraform_linter.yml
--- a/.github/workflows/terraform_linter.yml
+++ b/.github/workflows/terraform_linter.yml
@@ -3,7 +3,7 @@
 #
 # .NOTES
 #     Author     : Roman Rabodzei
-#     Version    : 1.0.240617
+#     Version    : 1.0.240616
 #
 #             _
 #         .__(.)<  (MEOW)
@@ -13,29 +13,46 @@
 name: Terraform Linter
 
 on:
-  push:
-    branches:
-      - '!main'
-    paths:
-      - ./terraform/*
   pull_request:
     branches:
       - main
     paths:
-      - ./terraform/*
+      - 'terraform/**'
 
 permissions:
   contents: read
 
-env:
-  working-directory: "./terraform"
-
 jobs:
   terraform_linter:
     runs-on: ubuntu-latest
+    environment: "linter"
     steps:
+      # Checkout the repository to the GitHub Actions runner
       - name: Checkout
         uses: actions/checkout@v4
         with:
-          path: ${{ env.working-directory }}
           fetch-depth: 0
+      
+      # Install the preferred version of Terraform CLI 
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+      
+      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+      - name: Terraform Init
+        id: init
+        run: |
+          terraform init -backend=false
+
+      # Run a terraform fmt for push
+      - name: Terraform Format
+        id: fmt
+        run: \
+          terraform fmt -recursive -check 
+
+      # Run a terraform validate
+      # Run even if formatting fails
+      - name: Terraform Validate
+        id: validate
+        if: (success() || failure())
+        run: |
+          terraform validate
